ARG PHP_VERSION=8.3-apache
FROM php:${PHP_VERSION}

ARG COMPOSER_VERSION=2.8.5
ARG TZ="Europe/Madrid"

# Zona ordutegia konfirguratu
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone \
    && printf '[Date]\ndate.timezone="%s"\n' ${TZ} > /usr/local/etc/php/conf.d/tzone.ini

# PHP pakete eta liburutegiak instalatu
RUN apt update \
    && apt install -y --no-install-recommends \
       git acl openssl openssh-client wget zip unzip \
       libpng-dev zlib1g-dev libzip-dev libxml2-dev libicu-dev \
       libldap2-dev libxrender1 libxext6 libfontconfig1 libssl-dev \
       libxslt-dev supervisor \
    && docker-php-ext-install intl pdo gd zip pdo_mysql xml xsl \
    && docker-php-ext-configure ldap --with-libdir=lib/$(uname -m)-linux-gnu/ \
    && docker-php-ext-install ldap \
    && pecl install xdebug apcu \
    && docker-php-ext-enable opcache apcu \
    && apt-get install -y default-jre pdftk-java \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*

# Redis instalatu
RUN pecl install redis-5.3.7 \
    && docker-php-ext-enable redis \
    &&  rm -rf /tmp/pear

# Karpeta estruktura sortu eta baimenak balioztatu
RUN mkdir -p /var/www/html /var/cache/fontconfig /var/www/html/var/cache/dev/snappy /var/www/html/public/uploads \
    && chown -R www-data:www-data /var/cache/fontconfig /var/www/html/var/cache/dev/snappy /var/www/html/public/uploads

# Composer instalatu
RUN curl -sS https://getcomposer.org/installer | php -- --version=${COMPOSER_VERSION} \
    && mv composer.phar /usr/local/bin/composer

# Konfigurazioak
COPY ./docker/php/conf/php.ini  /usr/local/etc/php/conf.d/php.ini

COPY ./docker/php/conf/default.conf /etc/apache2/sites-available/default.conf
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf \
    && a2enmod rewrite ssl\
    && a2dissite 000-default \
    && a2ensite default


# PID zaharra ezabatu eta apache abiarazi
ENTRYPOINT ["sh", "-c", "rm -f /var/run/apache2/apache2.pid && apache2-foreground"]

WORKDIR /var/www/html
